In [1]:
import pandas as pd

df = pd.read_csv('loan.csv')

df.head()

         지역코드  성별    신용대출     담보대출
0  4100000000   1  688608  5706058
1  4100000000   2  611035  2260521
2  4100000001   1  125392  5946493
3  4100000001   2  239679  4711962
4  4100000002   1  623758  5411745

In [5]:
df_g = df.groupby(by=['지역코드','성별']).sum()
df_g['총대출액'] = df_g['신용대출'] + df_g['담보대출']
df_g.head()

                  신용대출      담보대출      총대출액
지역코드       성별
4100000000 1   1982040  20909941  22891981
           2   1956534  16383075  18339609
4100000001 1   1546019  32651664  34197683
           2   1459795  16135762  17595557
4100000002 1   1327812  11791205  13119017

In [7]:
df_g = df_g.unstack()

In [22]:
df_g['차이'] = abs(df_g['총대출액'][1] - df_g['총대출액'][2])
df_g = df_g.sort_values(by='차이', ascending=False)
df_g['차이'].idxmax()

np.int64(4100000278)