In [1]:
import pandas as pd

df = pd.read_csv('hr.csv')

In [2]:
df.head()

    사원번호         부서 성과등급         연봉  근속연수  교육참가횟수  만족도
0  E0001  Marketing    B   73200000  14.0       5  6.0
1  E0002         IR    A   95100000   3.0       4  9.0
2  E0003    Manager    B   44700000   5.0       2  8.0
3  E0004         IR    B  122100000  16.0       3  8.0
4  E0005         IR    C   66000000   NaN       4  8.0

In [3]:
df.isnull().sum()

사원번호        0
부서          0
성과등급        0
연봉          0
근속연수       48
교육참가횟수      0
만족도       120
dtype: int64

In [4]:
df['만족도'] = df['만족도'].fillna(df['만족도'].mean())
df.isnull().sum()

사원번호       0
부서         0
성과등급       0
연봉         0
근속연수      48
교육참가횟수     0
만족도        0
dtype: int64

In [9]:
fillna_value = df.groupby(['부서', '성과등급'])['근속연수'].transform("mean").astype(int)
df['근속연수'] = df['근속연수'].fillna(fillna_value)
df.isnull().sum()

사원번호      0
부서        0
성과등급      0
연봉        0
근속연수      0
교육참가횟수    0
만족도       0
dtype: int64

In [ ]:
df['연봉/근속연수'] = df['연봉'] / df['근속연수']
df['연봉/만족도'] = df['연봉'] / df['만족도']
df.head()

,사원번호,부서,성과등급,연봉,근속연수,교육참가횟수,만족도,연봉/근속연수,연봉/만족도
0,E0001,Marketing,B,73200000,14.0,5,6.0,5.228571e+06,1.220000e+07
1,E0002,IR,A,95100000,3.0,4,9.0,3.170000e+07,1.056667e+07
2,E0003,Manager,B,44700000,5.0,2,8.0,8.940000e+06,5.587500e+06
3,E0004,IR,B,122100000,16.0,3,8.0,7.631250e+06,1.526250e+07
4,E0005,IR,C,66000000,10.0,4,8.0,6.600000e+06,8.250000e+06

In [15]:
a = df.sort_values('연봉/근속연수', ascending=False).iloc[2]['근속연수']

In [16]:
b = df.sort_values('연봉/만족도', ascending=False).iloc[1]['교육참가횟수']

In [17]:
int(a+b)

7