In [2]:
import pandas as pd

df = pd.read_csv("design.csv")

df.head()

   id     design        c1        c2        c3        c4        c5
0   1  58.962471  0.374540  0.642032  0.103124  0.168935  0.707239
1   2  42.006534  0.950714  0.084140  0.902553  0.278590  0.152539
2   3  55.831980  0.731994  0.161629  0.505252  0.177010  0.576288
3   4  64.458592  0.598658  0.898554  0.826457  0.088703  0.606715
4   5  61.342792  0.156019  0.606429  0.320050  0.120636  0.424131

In [ ]:
train = df[:140]
test  = df[140:]

      id     design        c1        c2        c3        c4        c5
135  136  58.457931  0.323203  0.040729  0.944766  0.877201  0.272307
136  137  66.020866  0.518791  0.855461  0.849647  0.392445  0.018391
137  138  63.945956  0.703019  0.703658  0.247348  0.816599  0.914299
138  139  54.083051  0.363630  0.474174  0.450544  0.439135  0.117751
139  140  55.031334  0.971782  0.097834  0.129159  0.376944  0.576516

In [ ]:
from statsmodels.formula.api import ols

formula = "design ~ c1 + c2 + c3 + c4 + c5"
model = ols(formula, train).fit()
model.summary()

# 0.05보다 작은 변수: 3개

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 design   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                  0.238
Method:                 Least Squares   F-statistic:                     9.697
Date:                Wed, 17 Jun 2026   Prob (F-statistic):           6.37e-08
Time:                        12:08:56   Log-Likelihood:                -468.72
No. Observations:                 140   AIC:                             949.4
Df Residuals:                     134   BIC:                             967.1
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     53.0220      2.294     23.112      0.000      48.485      57.559
c1            -4.9403      2.008     -2.460      0.015      -8.912      -0.969
c2            11.3795      2.045      5.564      0.000       7.335      15.424
c3             2.6960      1.920      1.404      0.163      -1.101       6.493
c4             5.7978      2.176      2.664      0.009       1.494      10.102
c5            -1.5018      2.067     -0.726      0.469      -5.590       2.587
==============================================================================
Omnibus:                        3.969   Durbin-Watson:                   2.052
Prob(Omnibus):                  0.137   Jarque-Bera (JB):                3.019
Skew:                           0.227   Prob(JB):                        0.221
Kurtosis:                       2.441   Cond. No.                         7.68
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [5]:
formula = "design ~ c1 + c2 + c4"
model = ols(formula, train).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 design   R-squared:                       0.251
Model:                            OLS   Adj. R-squared:                  0.234
Method:                 Least Squares   F-statistic:                     15.17
Date:                Wed, 17 Jun 2026   Prob (F-statistic):           1.43e-08
Time:                        12:09:41   Log-Likelihood:                -470.14
No. Observations:                 140   AIC:                             948.3
Df Residuals:                     136   BIC:                             960.0
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     53.6637      1.808     29.686      0.000      50.089      57.239
c1            -4.8767      2.010     -2.426      0.017      -8.852      -0.901
c2            11.1863      2.039      5.487      0.000       7.154      15.218
c4             6.2272      2.159      2.885      0.005       1.958      10.496
==============================================================================
Omnibus:                        3.056   Durbin-Watson:                   1.972
Prob(Omnibus):                  0.217   Jarque-Bera (JB):                2.947
Skew:                           0.296   Prob(JB):                        0.229
Kurtosis:                       2.606   Cond. No.                         5.96
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
pred = model.predict(train)

In [14]:
from scipy.stats import pearsonr

round(pearsonr(train['design'], pred).statistic, 3)

np.float64(0.501)

In [15]:
from sklearn.metrics import root_mean_squared_error

pred = model.predict(test)
round(root_mean_squared_error(test['design'], pred), 3)

8.488