In [1]:
import pandas as pd

df = pd.read_csv('cafe_sales.csv')

In [2]:
df.head()

         order_date  category      item  price
0  2025.03.08 23:30       tea  GreenTea   6861
1  2025.10.01 13:05    coffee     Latte   6080
2  2025.04.30 17:32  smoothie     Mango   6116
3  2025.12.07 06:45       tea  BlackTea   7807
4  2024.04.10 00:40   dessert    Cookie   7964

In [3]:
df['order_date'] = pd.to_datetime(df['order_date'])

df['order_month'] = df['order_date'].dt.strftime('%Y%m')
df.head()

           order_date  category      item  price order_month
0 2025-03-08 23:30:00       tea  GreenTea   6861      202503
1 2025-10-01 13:05:00    coffee     Latte   6080      202510
2 2025-04-30 17:32:00  smoothie     Mango   6116      202504
3 2025-12-07 06:45:00       tea  BlackTea   7807      202512
4 2024-04-10 00:40:00   dessert    Cookie   7964      202404

In [7]:
sales = df.groupby('order_month')['price'].sum().sort_values(ascending=False)
sales.iloc[1]

np.int64(328741)

In [10]:
idx = sales.index[3]
idx

'202410'

In [15]:
cond = df['order_month'] == '202410'
cat_sales = df[cond].groupby('category')
cat_sales['price'].sum().max()

np.int64(104660)