In [10]:
import pandas as pd

df = pd.read_csv('./hamspam.csv')

In [11]:
df['words'] = df['text'].str.split()
df.head()

,label,text,words
0,ham,Incididunt tempor elit sit do aliqua eiusmod a...,"[Incididunt, tempor, elit, sit, do, aliqua, ei..."
1,ham,Adipiscing tempor lorem ipsum dolore tempor.,"[Adipiscing, tempor, lorem, ipsum, dolore, tem..."
2,spam,Tempor tempor magna sed incididunt consectetur.,"[Tempor, tempor, magna, sed, incididunt, conse..."
3,ham,Consectetur incididunt amet adipiscing amet lo...,"[Consectetur, incididunt, amet, adipiscing, am..."
4,ham,Sit ipsum labore sit do sit elit.,"[Sit, ipsum, labore, sit, do, sit, elit.]"

In [14]:
df['words_count'] = df['words'].str.len()
df.head()

,label,text,words,words_count
0,ham,Incididunt tempor elit sit do aliqua eiusmod a...,"[Incididunt, tempor, elit, sit, do, aliqua, ei...",10
1,ham,Adipiscing tempor lorem ipsum dolore tempor.,"[Adipiscing, tempor, lorem, ipsum, dolore, tem...",6
2,spam,Tempor tempor magna sed incididunt consectetur.,"[Tempor, tempor, magna, sed, incididunt, conse...",6
3,ham,Consectetur incididunt amet adipiscing amet lo...,"[Consectetur, incididunt, amet, adipiscing, am...",12
4,ham,Sit ipsum labore sit do sit elit.,"[Sit, ipsum, labore, sit, do, sit, elit.]",7

In [18]:
msg_mean = df.groupby('label')['words_count'].mean()

In [20]:
abs(round(msg_mean['spam'] - msg_mean['ham'], 3))

np.float64(0.047)