In [1]:
import pandas as pd

df = pd.read_csv('attrition.csv')
df.head()

   attrition  age  income  overtime
0          0   44    6467         1
1          0   41    6201         0
2          1   25    4017         1
3          0   28    6360         1
4          1   58    2369         0

In [2]:
df.isnull().sum()

attrition    0
age          0
income       0
overtime     0
dtype: int64

In [3]:
from statsmodels.formula.api import logit

formula = 'attrition ~ age + income + overtime'
model = logit(formula, df).fit()
model.summary()

# -0.002

Optimization terminated successfully.
         Current function value: 0.387298
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:              attrition   No. Observations:                 6000
Model:                          Logit   Df Residuals:                     5996
Method:                           MLE   Df Model:                            3
Date:                Tue, 16 Jun 2026   Pseudo R-squ.:                  0.4215
Time:                        23:22:58   Log-Likelihood:                -2323.8
converged:                       True   LL-Null:                       -4016.9
Covariance Type:            nonrobust   LLR p-value:                     0.000
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.7724      0.246     31.650      0.000       7.291       8.254
age           -0.0044      0.004     -1.208      0.227      -0.012       0.003
income        -0.0015   3.66e-05    -41.263      0.000      -0.002      -0.001
overtime       0.0397      0.074      0.537      0.592      -0.105       0.185
==============================================================================
"""

In [4]:
test = pd.DataFrame({
    'age': [40],
    'income': [4500],
    'overtime': [1]
})

test.head()

   age  income  overtime
0   40    4500         1

In [10]:
import numpy as np

round(np.exp(model.params['age']), 3)

np.float64(0.996)

In [6]:
round(model.predict(test)[0], 3)

np.float64(0.697)