In [8]:
import pandas as pd

train = pd.read_csv("./data/car_train.csv")
test  = pd.read_csv("./data/car_test.csv")

In [9]:
train.head()

,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,13956,603,LEXUS,RX 450,2015,Jeep,Yes,Hybrid,3.5,143619 km,6.0,Automatic,4x4,04-May,Left wheel,Black,12
1,26108,640,SSANGYONG,REXTON,2013,Jeep,Yes,Diesel,2,111307 km,4.0,Automatic,Front,04-May,Left wheel,White,4
2,549,1493,MERCEDES-BENZ,GLE 350,2016,Jeep,Yes,Petrol,3.5,91493 km,6.0,Automatic,Rear,04-May,Left wheel,Black,0
3,14113,475,FIAT,500,2012,Sedan,Yes,Petrol,1.4,88000 km,4.0,Tiptronic,Front,02-Mar,Left wheel,Black,6
4,21739,639,CHEVROLET,Orlando,2014,Jeep,Yes,Diesel,2,177103 km,4.0,Automatic,Front,04-May,Left wheel,White,4

In [10]:
test.head()

,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,730,SSANGYONG,Actyon,2016,Jeep,Yes,Petrol,1.6,70940 km,4.0,Automatic,Front,04-May,Left wheel,Black,4
1,609,TOYOTA,Camry,2018,Sedan,Yes,Hybrid,2.5,32000 km,4.0,Automatic,Front,04-May,Left wheel,Black,12
2,761,TOYOTA,Prius,2010,Hatchback,No,Hybrid,1.8,135797 km,4.0,Automatic,Front,04-May,Left wheel,Red,0
3,-,TOYOTA,Camry,2018,Sedan,Yes,Hybrid,2.4,14000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Blue,12
4,765,HYUNDAI,Santa FE,2015,Jeep,Yes,Diesel,2,94090 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

ValueError: No columns match the specified include or exclude data types

In [14]:
cols = train.select_dtypes(include='object').columns

for col in cols:
    set_train = set(train[col])
    set_test = set(test[col])

    same = set_train == set_test

    print(f"{col}: ", same)

Levy:  False
Manufacturer:  False
Model:  False
Category:  True
Leather interior:  True
Fuel type:  False
Engine volume:  False
Mileage:  False
Gear box type:  True
Drive wheels:  True
Doors:  True
Wheel:  True
Color:  True

/var/folders/kw/21c5kk913b949nnyjby2q78w0000gn/T/ipykernel_25999/1661419845.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cols = train.select_dtypes(include='object').columns

In [15]:
target = train.pop('Price')

from sklearn.preprocessing import LabelEncoder

combined = pd.concat([train, test])
cols = train.select_dtypes(include='object')

for col in cols:
    le = LabelEncoder()
    combined[col] = le.fit_transform(combined[col])

n_train = len(train)
train = combined[:n_train]
test = combined[n_train:]

/var/folders/kw/21c5kk913b949nnyjby2q78w0000gn/T/ipykernel_25999/4238664095.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cols = train.select_dtypes(include='object')

In [17]:
from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

In [19]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

In [20]:
from sklearn.metrics import root_mean_squared_log_error

result = root_mean_squared_log_error(y_val, pred)
print("score: ", result)

score:  1.1011992916981865

In [21]:
pred = rf.predict(test)
submit = pd.DataFrame({"pred": pred})
submit.to_csv("./submit/car_baseline_result.csv", index=False)