In [21]:
import pandas as pd
from os import path

train = pd.read_csv("./data/hr_train.csv")
test = pd.read_csv("./data/hr_test.csv")

In [22]:
# 데이터 크기
print("train: ", train.shape)
print("test :", test.shape)

train:  (15326, 14)
test : (3832, 13)

In [23]:
train.head(3)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,30266,city_84,0.698,Male,No relevent experience,Full time course,High School,NaN,1,100-500,Pvt Ltd,never,15,0.0
1,13254,city_16,0.910,Male,Has relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,1,4,0.0
2,31675,city_21,0.624,Male,No relevent experience,Full time course,High School,NaN,3,NaN,NaN,never,12,0.0

In [24]:
test.head(3)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours
0,23044,city_136,0.897,Female,No relevent experience,Full time course,Masters,STEM,8,100-500,Public Sector,1,35
1,29611,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,16,<10,Pvt Ltd,>4,134
2,22483,city_21,0.624,NaN,Has relevent experience,no_enrollment,Graduate,STEM,5,10000+,Pvt Ltd,1,92

In [25]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 15326 entries, 0 to 15325
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             15326 non-null  int64
 1   city                    15326 non-null  str
 2   city_development_index  15326 non-null  float64
 3   gender                  11750 non-null  str
 4   relevent_experience     15326 non-null  str
 5   enrolled_university     15012 non-null  str
 6   education_level         14961 non-null  str
 7   major_discipline        13045 non-null  str
 8   experience              15272 non-null  str
 9   company_size            10539 non-null  str
 10  company_type            10383 non-null  str
 11  last_new_job            14984 non-null  str
 12  training_hours          15326 non-null  int64
 13  target                  15326 non-null  float64
dtypes: float64(2), int64(2), str(10)
memory usage: 1.6 MB

In [26]:
train.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    3576
relevent_experience          0
enrolled_university        314
education_level            365
major_discipline          2281
experience                  54
company_size              4787
company_type              4943
last_new_job               342
training_hours               0
target                       0
dtype: int64

In [27]:
test.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                     932
relevent_experience          0
enrolled_university         72
education_level             95
major_discipline           532
experience                  11
company_size              1151
company_type              1197
last_new_job                81
training_hours               0
dtype: int64

In [28]:
target = train.pop('target')

In [ ]:
train = train.fillna('X')
test = test.fillna('X')

In [32]:
combined = pd.concat([train, test])
combined_dummies = pd.get_dummies(combined)
n_train = len(train)

In [ ]:
train = combined_dummies[:n_train]
test = combined_dummies[n_train:]

   enrollee_id  city_development_index  training_hours  city_city_1  \
0        30266                   0.698              15        False
1        13254                   0.910               4        False
2        31675                   0.624              12        False
3        30804                   0.924             258        False
4        18269                   0.740               3        False

   city_city_10  city_city_100  city_city_101  city_city_102  city_city_103  \
0         False          False          False          False          False
1         False          False          False          False          False
2         False          False          False          False          False
3         False          False          False          False          False
4         False          False          False          False          False

   city_city_104  ...  company_type_Public Sector  company_type_Pvt Ltd  \
0          False  ...                       False                  True
1          False  ...                       False                  True
2          False  ...                       False                 False
3           True  ...                       False                 False
4          False  ...                       False                  True

   company_type_X  last_new_job_1  last_new_job_2  last_new_job_3  \
0           False           False           False           False
1           False            True           False           False
2            True           False           False           False
3            True           False            True           False
4           False            True           False           False

   last_new_job_4  last_new_job_>4  last_new_job_X  last_new_job_never
0           False            False           False                True
1           False            False           False               False
2           False            False           False                True
3           False            False           False               False
4           False            False           False               False

[5 rows x 195 columns]

In [35]:
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict_proba(X_val)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [38]:
from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_val, pred[:,1])
print('roc_auc: ', roc_auc)

roc_auc:  0.7755723189159068

In [39]:
pred = rf.predict_proba(test)
submit = pd.DataFrame({'pred': pred[:,1]})
submit.to_csv("result.csv", index=False)