## 문제 4
제공된 학습용 데이터(train.csv)는 온라인 게임 플레이어의 활동 데이터이다. 학습용 데이터
를 활용하여 유저 등급(User_Level)을 예측하는 모형을 개발하고, 모형을 평가용 데이터(test.csv)에 적용하여 유저 등급을 예측하시오. 예측 결과는 아래의 [유의 사항]과 [제출 형식]을 준수하여, CSV 파 일(result.csv)을 생성하는 코드를 제출하시오.

### 유의 사항
1. 예측 결과는 F1 Score(macro) 평가 지표에 따라 평가함
2. 타겟 변수(User_Level)는 0, 1, 2 총 3개의 클래스로 구성됨 (O: Low, 1: Medium, 2: High)

### 제출 형식
1. CSV 파일명 : result.csv
2. 예측 유저 등급 컬럼명: pred
3. 제출 컬럼 개수: pred 컬럼 1개
4. 평가용 데이터 개수와 예측 결과 데이터 개수 일치: 903개

### 제공 데이터
- train.csv: 학습용 데이터, 약 2,614개
- test.csv: 평가용 데이터, 약 903개

### CSV 파일 형식 및 확인 방법
• CSV 파일명 : result.csv
• 예측 유저 등급 컬럼명 : pred
• 제출 CSV 파일 예시

```
Pred
0
1
1
0
2
1
```

In [1]:
import pandas as pd

train = pd.read_csv('game_train.csv')
test  = pd.read_csv('game_test.csv')

In [2]:
train.head()

,Guild_Contribution,Character_Level,Weekly_Playtime,Chat_Activity,Days_Inactive,Guild_Rank,PVP_Score,Quest_Completed,Item_Level,User_Level
0,184.76,20,46.11,97,14,0,397.70,93,230.45,0
1,987.68,120,58.79,0,0,5,999.00,471,250.54,2
2,274.90,40,41.66,136,0,8,633.58,245,253.44,1
3,581.71,83,15.56,186,1,3,144.42,0,200.18,1
4,129.14,19,28.74,135,4,3,240.33,209,176.01,0

In [3]:
test.head()

,Guild_Contribution,Character_Level,Weekly_Playtime,Chat_Activity,Days_Inactive,Guild_Rank,PVP_Score,Quest_Completed,Item_Level
0,634.80,47,29.47,103,18,1,193.46,240,143.62
1,318.91,45,24.57,176,12,0,173.30,0,205.63
2,182.23,1,18.98,159,6,1,227.91,152,100.00
3,590.06,13,13.23,67,16,0,294.10,400,196.88
4,276.95,56,34.14,277,2,0,401.53,434,402.83

In [4]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 2614 entries, 0 to 2613
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Guild_Contribution  2614 non-null   float64
 1   Character_Level     2614 non-null   int64
 2   Weekly_Playtime     2614 non-null   float64
 3   Chat_Activity       2614 non-null   int64
 4   Days_Inactive       2614 non-null   int64
 5   Guild_Rank          2614 non-null   int64
 6   PVP_Score           2614 non-null   float64
 7   Quest_Completed     2614 non-null   int64
 8   Item_Level          2614 non-null   float64
 9   User_Level          2614 non-null   int64
dtypes: float64(4), int64(6)
memory usage: 204.3 KB

In [5]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 903 entries, 0 to 902
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Guild_Contribution  903 non-null    float64
 1   Character_Level     903 non-null    int64
 2   Weekly_Playtime     903 non-null    float64
 3   Chat_Activity       903 non-null    int64
 4   Days_Inactive       903 non-null    int64
 5   Guild_Rank          903 non-null    int64
 6   PVP_Score           903 non-null    float64
 7   Quest_Completed     903 non-null    int64
 8   Item_Level          903 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 63.6 KB

In [6]:
train.isnull().sum()

Guild_Contribution    0
Character_Level       0
Weekly_Playtime       0
Chat_Activity         0
Days_Inactive         0
Guild_Rank            0
PVP_Score             0
Quest_Completed       0
Item_Level            0
User_Level            0
dtype: int64

In [7]:
test.isnull().sum()

Guild_Contribution    0
Character_Level       0
Weekly_Playtime       0
Chat_Activity         0
Days_Inactive         0
Guild_Rank            0
PVP_Score             0
Quest_Completed       0
Item_Level            0
dtype: int64

In [8]:
train.describe()

,Guild_Contribution,Character_Level,Weekly_Playtime,Chat_Activity,Days_Inactive,Guild_Rank,PVP_Score,Quest_Completed,Item_Level,User_Level
count,2614.000000,2614.000000,2614.000000,2614.000000,2614.000000,2614.000000,2614.000000,2614.000000,2614.000000,2614.000000
mean,392.675750,52.605203,31.471106,142.390207,9.388294,3.009181,380.917169,339.258607,283.524778,0.606350
std,230.474546,29.107693,17.584983,91.363532,7.489523,2.545850,226.774082,173.032812,119.121550,0.585556
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,0.000000
25%,213.240000,31.000000,17.520000,70.000000,3.000000,1.000000,203.517500,215.000000,185.395000,0.000000
50%,360.935000,53.000000,29.075000,136.000000,8.000000,3.000000,347.065000,336.500000,272.675000,1.000000
75%,539.545000,74.000000,42.847500,204.000000,14.000000,5.000000,512.862500,454.750000,371.160000,1.000000
max,987.680000,120.000000,70.000000,400.000000,30.000000,10.000000,999.000000,800.000000,500.000000,2.000000

In [9]:
test.describe()

,Guild_Contribution,Character_Level,Weekly_Playtime,Chat_Activity,Days_Inactive,Guild_Rank,PVP_Score,Quest_Completed,Item_Level
count,903.000000,903.000000,903.000000,903.000000,903.000000,903.000000,903.000000,903.000000,903.000000
mean,396.095748,54.522702,32.955559,142.585825,9.191584,3.124031,386.944408,345.274640,286.540122
std,229.752335,28.576681,17.859075,90.998654,7.191848,2.563627,228.075766,171.431277,118.433543
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000
25%,219.815000,33.500000,18.585000,70.000000,3.000000,1.000000,212.270000,218.500000,188.855000
50%,357.370000,55.000000,31.390000,138.000000,8.000000,3.000000,351.770000,342.000000,277.710000
75%,551.135000,75.000000,44.990000,207.000000,14.000000,5.000000,511.115000,460.000000,367.730000
max,987.680000,120.000000,70.000000,400.000000,30.000000,10.000000,999.000000,800.000000,500.000000

In [10]:
target = train.pop('User_Level')

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=0)
print(X_train.shape, X_val.shape)
print(y_train.shape, y_val.shape)

(2091, 9) (523, 9)
(2091,) (523,)

In [12]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=0)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_val)

In [13]:
from lightgbm import LGBMClassifier

lg = LGBMClassifier(random_state=0, verbose=-1)
lg.fit(X_train, y_train)
lg_pred = lg.predict(X_val)

array([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 1, 1, 1, 1, 2, 2, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 2, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2,
       0, 0, 0, 1, 2, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 1, 0, 0, 1, 2,
       1, 0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 2, 1,
       1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1])

In [15]:
from sklearn.metrics import f1_score

rf_score = f1_score(y_val, rf_pred, average='macro')
rf_score

0.7241845968568211

In [16]:
lg_score = f1_score(y_val, lg_pred, average='macro')
lg_score

0.7989718332478102

In [20]:
pred = lg.predict(test)

result = pd.DataFrame({ 'Pred': pred })
result.to_csv('result.csv', index=False)