## 문제 5
제공된 데이터(`promotion_data.csv`)는 기업의 마케팅 홍보 활동에 따른 매출 데이터로, 방문 횟수, 웹페이지 방문 시간, 광고 클릭 수, 홍보 예산 등에 따른 매출액(sales)에 관한 자료이다. 이 데이 터를 이용하여 통계 분석을 수행하고, 제시된 소문항에 답하시오.

> 제공 데이터 (promotion_data.csv)
> - 종속 변수 (타겟 변수): sales, 매출액
> - 독립 변수 (설명 변수):
> - VISI_count: 방문 횟수
> - page_time: 웹페이지 방문 시간(초)
> - ad_clicks: 광고 클릭 수
> - promotion_budget: 홍보 예산
> ```python
> import pandas as pd
> df = pd.read_csv("promotion_data.csv")
> ```

1. 홍보 전후 매출 평균이 35,000원과 같은지 단일 t검정(t-lest)을 수행하고, p-value를 구하시오. (반올
림하여 소수 셋째 자리까지 작성)
2. 매출액(sales)과 다른 모든 변수들 간의 피어슨 상관계수를 구하고, 그 중 상관관계가 가장 강한(절댓
값이 가장 큰) 상관계수 값을 구하시오. (반올림하여 소수 셋째 자리까지 작성)
3. 매출액(sales)을 종속변수로, 나머지 모든 변수를 독립변수로 하여 회귀분석을 수행하시오. 절편을 포
함한 모든 변수 중에서 p-value가 가장 작은 변수(통계적으로 가장 유의한 변수)의 회귀계수를 구하시오. (반올림 하여 소수 셋째 자리까지 작성)

In [1]:
import pandas as pd
df = pd.read_csv("promotion_data.csv")

In [2]:
df.head()

          sales  visit_count  page_time  ad_clicks  promotion_budget
0  35341.611727           36        168         18             11340
1  64757.849132           32        214         21             11224
2  40615.684241           56        172          6              5468
3  52009.480757           70        234          5              7486
4  32462.259065           27         88          8              7547

In [5]:
from scipy.stats import ttest_1samp

statistics, pvalue = ttest_1samp(df['sales'], 35000)

pvalue > 0.05

np.True_

In [ ]:
from scipy.stats import pearsonr

# pearsonr()
df.corr(method='pearson')

# 0.575396

,sales,visit_count,page_time,ad_clicks,promotion_budget
sales,1.000000,0.044154,0.575396,-0.131915,-0.091270
visit_count,0.044154,1.000000,0.011349,0.078189,-0.089217
page_time,0.575396,0.011349,1.000000,-0.093688,-0.039554
ad_clicks,-0.131915,0.078189,-0.093688,1.000000,0.036940
promotion_budget,-0.091270,-0.089217,-0.039554,0.036940,1.000000

In [ ]:
from statsmodels.formula.api import ols

formula = 'sales ~ visit_count + page_time + ad_clicks + promotion_budget'
model = ols(formula, df).fit()
model.summary()

# p-value가 가장 작은 변수는 page_time
# 회귀계수는 130.7392

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.343
Model:                            OLS   Adj. R-squared:                  0.330
Method:                 Least Squares   F-statistic:                     25.45
Date:                Tue, 16 Jun 2026   Prob (F-statistic):           5.60e-17
Time:                        20:01:08   Log-Likelihood:                -2160.2
No. Observations:                 200   AIC:                             4330.
Df Residuals:                     195   BIC:                             4347.
Df Model:                           4
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept         2.234e+04   4136.622      5.400      0.000    1.42e+04    3.05e+04
visit_count         28.7893     43.854      0.656      0.512     -57.701     115.279
page_time          130.7392     13.501      9.684      0.000     104.113     157.365
ad_clicks         -116.0846     85.288     -1.361      0.175    -284.290      52.121
promotion_budget    -0.3601      0.336     -1.072      0.285      -1.023       0.303
==============================================================================
Omnibus:                        0.318   Durbin-Watson:                   1.941
Prob(Omnibus):                  0.853   Jarque-Bera (JB):                0.286
Skew:                          -0.091   Prob(JB):                        0.867
Kurtosis:                       2.970   Cond. No.                     3.63e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.63e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""