In [14]:
import pandas as pd

train = pd.read_csv("./data/score_train.csv")
test  = pd.read_csv("./data/score_test.csv")

In [15]:
print("train: ", train.shape)
print("test : ", test.shape)

train:  (4198, 21)
test :  (1499, 20)

In [16]:
train.head(1)

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Mix,Payment_Behaviour,...,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month,Credit_Score
0,26.0,10.0,5.0,30.358905,200.0,NM,192.3418,321.431503,Good,Low_spent_Small_value_payments,...,36963.89,0.0,4.0,1.0,2.0,2902.324167,6.47,1195.96,46.459114,Standard

In [17]:
test.head(1)

,Delay_from_due_date,Num_of_Delayed_Payment,Num_Credit_Inquiries,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Amount_invested_monthly,Monthly_Balance,Credit_Mix,Payment_Behaviour,Age,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Monthly_Inhand_Salary,Changed_Credit_Limit,Outstanding_Debt,Total_EMI_per_month
0,19.0,20.0,11.0,28.893968,57.0,Yes,126.895309,217.045508,Bad,Low_spent_Small_value_payments,21.0,16644.79,7.0,6.0,24.0,9.0,1547.065833,9.93,3519.49,100.765767

In [18]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 1499 entries, 0 to 1498
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       1499 non-null   float64
 1   Num_of_Delayed_Payment    1499 non-null   float64
 2   Num_Credit_Inquiries      1499 non-null   float64
 3   Credit_Utilization_Ratio  1499 non-null   float64
 4   Credit_History_Age        1499 non-null   float64
 5   Payment_of_Min_Amount     1499 non-null   str
 6   Amount_invested_monthly   1499 non-null   float64
 7   Monthly_Balance           1499 non-null   float64
 8   Credit_Mix                1499 non-null   str
 9   Payment_Behaviour         1499 non-null   str
 10  Age                       1499 non-null   float64
 11  Annual_Income             1499 non-null   float64
 12  Num_Bank_Accounts         1499 non-null   float64
 13  Num_Credit_Card           1499 non-null   float64
 14  Interest_Rate             1499 non-null   float64
 15  Num_of_Loan               1499 non-null   float64
 16  Monthly_Inhand_Salary     1499 non-null   float64
 17  Changed_Credit_Limit      1499 non-null   float64
 18  Outstanding_Debt          1499 non-null   float64
 19  Total_EMI_per_month       1499 non-null   float64
dtypes: float64(17), str(3)
memory usage: 234.3 KB

In [19]:
train.isnull().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
Credit_Score                0
dtype: int64

In [20]:
test.isnull().sum()

Delay_from_due_date         0
Num_of_Delayed_Payment      0
Num_Credit_Inquiries        0
Credit_Utilization_Ratio    0
Credit_History_Age          0
Payment_of_Min_Amount       0
Amount_invested_monthly     0
Monthly_Balance             0
Credit_Mix                  0
Payment_Behaviour           0
Age                         0
Annual_Income               0
Num_Bank_Accounts           0
Num_Credit_Card             0
Interest_Rate               0
Num_of_Loan                 0
Monthly_Inhand_Salary       0
Changed_Credit_Limit        0
Outstanding_Debt            0
Total_EMI_per_month         0
dtype: int64

In [21]:
target = train.pop('Credit_Score')

train = pd.get_dummies(train)
test  = pd.get_dummies(test)

In [22]:
from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)
print(X_tr.shape, X_val.shape, y_tr.shape, y_val.shape)

(3358, 29) (840, 29) (3358,) (840,)

In [23]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

In [24]:
from sklearn.metrics import f1_score
f1 = f1_score(y_val, pred, average='macro')
print("f1 score: ", f1)

f1 score:  0.7019165695111894

In [25]:
pred = rf.predict(test)
submit = pd.DataFrame(pred)
submit.to_csv("./submit/creditscore_baseline_result.csv", index=False)