In [1]:
import pandas as pd
df = pd.DataFrame({
    '할인율': [28, 24, 13, 0, 27, 30, 10, 16, 6, 5, 7, 11, 11, 30, 25,
            4, 7, 24, 19, 21, 6, 10, 26, 13, 15, 6, 12, 6, 20, 2],
    '온도': [15, 34, 15, 22, 29, 30, 14, 17, 28, 29, 19, 19, 34, 10,
           29, 28, 12, 25, 32, 28, 22, 16, 30, 11, 16, 18, 16, 33, 12, 22],
    '광고비': [342, 666, 224, 764, 148, 499, 711, 596, 797, 484, 986, 347, 146, 362, 642,
            591, 846, 260, 560, 941, 469, 309, 730, 305, 892, 147, 887, 526, 525, 884],
    '주문량': [635, 958, 525, 25, 607, 872, 858, 732, 1082, 863, 904, 686, 699, 615, 893,
            830, 856, 679, 918, 951, 789, 583, 988, 631, 866, 549, 910, 946, 647, 943]
})
print(df.head(3))

   할인율  온도  광고비  주문량
0   28  15  342  635
1   24  34  666  958
2   13  15  224  525

In [3]:
from statsmodels.formula.api import ols

model = ols("주문량~할인율 + 온도 + 광고비", df).fit()

In [4]:
df['할인율'].corr(df['온도'])

np.float64(0.0939279527627748)

In [5]:
model.rsquared

np.float64(0.3996744205683782)

In [7]:
model.params

Intercept    267.660902
할인율            4.206829
온도             9.479843
광고비            0.414827
dtype: float64

In [8]:
model.pvalues

Intercept    0.049625
할인율          0.246660
온도           0.028867
광고비          0.002740
dtype: float64

In [10]:
test = pd.DataFrame({
    '할인율': [10],
    '온도': [20],
    '광고비': [500],
})
test.head()

   할인율  온도  광고비
0   10  20  500

In [11]:
result = model.predict(test)

In [13]:
result

0    706.739338
dtype: float64

In [14]:
df['잔차'] = df['주문량'] - model.predict(df)

In [15]:
df.head()

   할인율  온도  광고비  주문량          잔차
0   28  15  342  635  -34.520451
1   24  34  666  958   -9.213960
2   13  15  224  525  -32.468478
3    0  22  764   25 -768.144947
4   27  29  148  607 -110.555069

In [16]:
ssr = round(sum(df['잔차']**2), 2)

In [17]:
ssr

732197.9

In [18]:
mse = (df['잔차'] ** 2).mean()
mse

np.float64(24406.596627140243)

In [19]:
model.conf_int(alpha=0.1)

                   0           1
Intercept  45.955720  489.366084
할인율        -1.847229   10.260887
온도          2.490702   16.468984
광고비         0.201064    0.628589

In [20]:
test_2 = pd.DataFrame({
    '할인율': [10],
    '온도': [25],
    '광고비': [300],
})

pred = model.get_prediction(test)

In [21]:
pred.summary_frame(alpha=0.1)

,mean,mean_se,mean_ci_lower,mean_ci_upper,obs_ci_lower,obs_ci_upper
0,706.739338,36.456283,644.558848,768.919829,413.836923,999.641754

In [22]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    주문량   R-squared:                       0.400
Model:                            OLS   Adj. R-squared:                  0.330
Method:                 Least Squares   F-statistic:                     5.770
Date:                Mon, 15 Jun 2026   Prob (F-statistic):            0.00366
Time:                        17:52:17   Log-Likelihood:                -194.11
No. Observations:                  30   AIC:                             396.2
Df Residuals:                      26   BIC:                             401.8
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    267.6609    129.985      2.059      0.050       0.472     534.849
할인율            4.2068      3.549      1.185      0.247      -3.089      11.503
온도             9.4798      4.098      2.313      0.029       1.057      17.903
광고비            0.4148      0.125      3.310      0.003       0.157       0.672
==============================================================================
Omnibus:                       56.788   Durbin-Watson:                   1.647
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              419.005
Skew:                          -3.845   Prob(JB):                     1.03e-91
Kurtosis:                      19.616   Cond. No.                     2.58e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.58e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""